routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/customer');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('customer', 'CustomersController');
    Route::get('/customer/{id}/delete', 'CustomersController@delete');
    
    Route::resource('payments', 'PaymentsController');
    Route::get('/payments/{id}/delete', 'PaymentsController@delete');
    Route::get('/payments/{id}/receipt', 'PaymentsController@receipt');
    Route::get('/payments/{id}/receipt-dp', 'PaymentsController@receipt_dp');
    Route::get('/payments/{id}/update-dp', 'PaymentsController@update_dp');
    
    Route::resource('occupants', 'OccupantsController');
    Route::get('/occupants/{id}/delete', 'OccupantsController@delete');
    
    Route::resource('room', 'RoomsController');
    Route::get('/room/{id}/delete', 'RoomsController@delete');
    
    Route::resource('room-type', 'RoomTypesController');
    Route::get('/room-type/{id}/delete', 'RoomTypesController@delete');
    
    Route::resource('additional-facilities', 'AdditionalFacilitiesController');
    Route::get('/additional-facilities/{id}/delete', 'AdditionalFacilitiesController@delete');
});

app/RoomTypes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RoomTypes extends Model
{
    protected $fillable = [
        'type_name',
        'size_bed',
        'desk',
        'wardrobe',
        'air_conditioner',
        'line_telp',
        'wifi',
        'bathroom',
        'water_heater',
        'private_balkon'
    ];

    public function room()
    {
        return $this->belongsTo('App\Rooms', 'id');
    }
}

app/Rooms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rooms extends Model
{
    protected $fillable = [
        'room_type_id',
        'occupant_id',
        'no_room',
        'location',
        'size_room',
        'cost_per_day',
        'cost_per_month',
        'cost_per_year',
        'ket_room'
    ];

    public function room_types()
    {
        return $this->hasOne('App\RoomTypes', 'id', 'room_type_id');
    }

    public function occupants()
    {
        return $this->hasOne('App\Occupants', 'id', 'occupant_id');
    }
}

app/Http/Controllers/RoomsController.php
<?php

namespace App\Http\Controllers;

use App\Rooms;
use App\RoomTypes;
use Carbon\Carbon;
use Illuminate\Http\Request;

class RoomsController extends Controller
{
    public function index()
    {
        $data['rooms'] = Rooms::all();
        $data['today'] = Carbon::now()->toDateString();
        $data['options'] = RoomTypes::select('type_name', 'id')->get();
        // dd($data);

        return view('room.index', $data);
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $req_rooms = [
            'room_type_id' => $request->room_type_id,
            'no_room' => $request->no_room,
            'location' => $request->location,
            'size_room' => $request->size_room,
            'cost_per_day' => $request->cost_per_day,
            'cost_per_month' => $request->cost_per_month,
            'cost_per_year' => $request->cost_per_year,
            'ket_room' => $request->ket_room,
        ];
        Rooms::create($req_rooms);

        return redirect('/room');
    }

    public function show($id)
    {
        $data['room'] = Rooms::FindOrFail($id);
        return view('room.detail', $data);
    }

    public function edit($id)
    {
        $data['options'] = RoomTypes::select('type_name', 'id')->get();
        $data['room'] = Rooms::FindOrFail($id);
        return view('room.edit', $data);
    }

    public function update($id, Request $request)
    {
        $data = $request->except('_method', '_token');
        Rooms::FindOrFail($id)->update($data);

        return redirect('/room');
    }

    public function delete($id)
    {
        Rooms::FindOrFail($id)->delete();
        return redirect()->back();
    }
}

resources/views/room/add.blade.php
<div class="modal fade" id="modal-add">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Kamar</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="panel">
                    <div class="panel-body">
                        <form action="{{ route('room.store')}}" method="POST" data-parsley-validate="true" enctype="multipart/form-data">
                            @csrf
                            <fieldset>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Tipe Kamar</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <select class="form-control selectpicker" name="room_type_id" data-size="5" data-width="100%" data-live-search="true" data-style="btn-white">
                                                    <option value="">- Pilih Tipe Kamar -</option>
                                                    @foreach ($options as $option)
                                                    <option value="{{$option->id}}">{{$option->type_name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">No Kamar</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="no_room" placeholder="Contoh: 201" />
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Lokasi</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="location" placeholder="Contoh: Lantai 1" />
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Ukuran Kamar</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="size_room" placeholder="Contoh: 4x2,6" />
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Biaya Per Hari (Rp)</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="cost_per_day" placeholder="Contoh: 150000" data-parsley-type="number"/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Biaya Per Bulan (Rp)</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="cost_per_month" placeholder="Contoh: 1800000" data-parsley-type="number"/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Biaya Per Tahun (Rp)</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="cost_per_year" placeholder="Contoh: 20000000" data-parsley-type="number"/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Keterangan</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <textarea class="form-control" rows="3" name="ket_room" placeholder="Keterangan"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Tutup</a>
                                    <button type="reset" class="btn btn-sm btn-danger" onclick="return confirm('Anda yakin akan reset form?')">Reset</button>
                                    <button type="submit" class="btn btn-sm btn-primary m-r-5">Simpan</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/room/detail.blade.php
@extends('layouts.app')

@section('sidebar')
@parent
@endsection

@section('content')
<ol class="breadcrumb pull-right">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/room">Data Kamar</a></li>
    <li class="breadcrumb-item active">Detail Data Kamar</li>
</ol>
<h1 class="page-header">Data Kamar</h1>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-inverse" data-sortable-id="form-stuff-10">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">Detail Data Kamar</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <dl>
                            <dt class="text-inverse m-t-10">Tipe Kamar</dt>
                            <dd>{{$room->room_types->type_name}}</dd>
                            <dt class="text-inverse m-t-10">No Kamar</dt>
                            <dd>{{$room->no_room}}</dd>
                            <dt class="text-inverse m-t-10">Lokasi Kamar</dt>
                            <dd>{{$room->location}}</dd>
                            <dt class="text-inverse m-t-10">Ukuran Kamar</dt>
                            <dd>{{$room->size_room}}</dd>
                        </dl>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <dl>
                            <dt class="text-inverse m-t-10">Biaya Per Hari (Rp)</dt>
                            <dd>{{$room->cost_per_day}}</dd>
                            <dt class="text-inverse m-t-10">Biaya Per Bulan (Rp)</dt>
                            <dd>{{$room->cost_per_month}}</dd>
                            <dt class="text-inverse m-t-10">Biaya Per Tahun (Rp)</dt>
                            <dd>{{$room->cost_per_year}}</dd>
                            <dt class="text-inverse m-t-10">Keterangan</dt>
                            <dd>{{$room->ket_room}}</dd>
                        </dl>
                    </div>
                </div><hr>
                <div>
                    <h4><i class="fa fa-wifi fa-fw"></i> Fasilitas Kamar</h4>
                </div><br>
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <dl>
                            <dt class="text-inverse m-t-10">Ukuran Tempat Tidur</dt>
                            <dd>{{$room->room_types->size_bed}}</dd>
                            <dt class="text-inverse m-t-10">Meja Belajar</dt>
                            <dd>{{$room->room_types->desk}}</dd>
                            <dt class="text-inverse m-t-10">Almari</dt>
                            <dd>{{$room->room_types->wardrobe}}</dd>
                            <dt class="text-inverse m-t-10">AC</dt>
                            <dd>{{$room->room_types->air_conditioner}}</dd>
                            <dt class="text-inverse m-t-10">Telp Kamar</dt>
                            <dd>{{$room->room_types->line_telp}}</dd>
                        </dl>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <dl>
                            <dt class="text-inverse m-t-10">Wifi</dt>
                            <dd>{{$room->room_types->wifi}}</dd>
                            <dt class="text-inverse m-t-10">Kamar Mandi Dalam</dt>
                            <dd>{{$room->room_types->bathroom}}</dd>
                            <dt class="text-inverse m-t-10">Water Heater</dt>
                            <dd>{{$room->room_types->water_heater}}</dd>
                            <dt class="text-inverse m-t-10">Privat Balkon</dt>
                            <dd>{{$room->room_types->private_balkon}}</dd>
                        </dl>
                    </div>
                </div><hr>
                <div>
                    <h4><i class="fa fa-info-circle fa-fw"></i>Status Kamar:  <span class="badge badge-{{($room->occupant_id != null) ? "danger" : "green" }} badge-square">  {{($room->occupant_id != null) ? "Sudah Terisi" : "Kosong" }}</span></h4>
                </div><br>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
@parent
@endsection

resources/views/room/roomFacilities_add.blade.php
<div class="modal fade" id="modal-add">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Fasilitas Tambahan</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="panel">
                    <div class="panel-body">
                        <form action="{{ route('additional-facilities.store')}}" method="POST" data-parsley-validate="true" enctype="multipart/form-data">
                            @csrf
                            <fieldset>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Nama Fasilitas</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="facilities_name" placeholder="Contoh: Loundry" required/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Biaya (Rp)</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="cost" placeholder="Contoh: 300000" data-parsley-type="number"/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Keterangan</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <textarea class="form-control" rows="3" name="ket" placeholder="Contoh: Loundry dengan sistem antar jemput"></textarea>
                                            </div>
                                        </div>
                                        <br>
                                        <div class="note note-warning">
                                            <div class="note-icon"><i class="fa fa-lightbulb"></i></div>
                                            <div class="note-content">
                                                <h4 class="m-t-5 m-b-5 p-b-2">Notes:</h4>
                                                <ul class="m-b-5 p-l-25">
                                                    <li>Mengisi kolom biaya hanya <strong>angka saja</strong> tanpa menggunakan titik</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Tutup</a>
                                    <button type="reset" class="btn btn-sm btn-danger" onclick="return confirm('Anda yakin akan reset form?')">Reset</button>
                                    <button type="submit" class="btn btn-sm btn-primary m-r-5">Simpan</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/room/roomType_add.blade.php
<div class="modal fade" id="modal-add">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Tipe Kamar</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="panel">
                    <div class="panel-body">
                        <form action="{{ route('room-type.store')}}" method="POST" data-parsley-validate="true" enctype="multipart/form-data">
                            @csrf
                            <fieldset>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Nama Tipe</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="type_name" placeholder="Contoh: Tipe 1" required/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Ukuran Tempat Tidur</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="size_bed" placeholder="Contoh: 160x200 cm" required/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Meja Belajar</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="desk" id="rd_desk1" value="Ada" required/>
                                                <label for="rd_desk1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="desk" id="rd_desk2" value="Tidak Ada"/>
                                                <label for="rd_desk2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Almari</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="wardrobe" id="rd_wardrobe1" value="Ada" required/>
                                                <label for="rd_wardrobe1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="wardrobe" id="rd_wardrobe2" value="Tidak Ada"/>
                                                <label for="rd_wardrobe2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">AC</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="air_conditioner" id="rd_air_conditioner1" value="Ada" required/>
                                                <label for="rd_air_conditioner1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="air_conditioner" id="rd_air_conditioner2" value="Tidak Ada"/>
                                                <label for="rd_air_conditioner2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Telp Kamar</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="line_telp" id="rd_line_telp1" value="Ada" required/>
                                                <label for="rd_line_telp1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="line_telp" id="rd_line_telp2" value="Tidak Ada"/>
                                                <label for="rd_line_telp2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Wi-Fi</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="wifi" id="rd_wifi1" value="Ada" required/>
                                                <label for="rd_wifi1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="wifi" id="rd_wifi2" value="Tidak Ada"/>
                                                <label for="rd_wifi2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Kamar Mandi Dalam</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="bathroom" id="rd_bathroom1" value="Ada" required/>
                                                <label for="rd_bathroom1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="bathroom" id="rd_bathroom2" value="Tidak Ada"/>
                                                <label for="rd_bathroom2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Water Heater</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="water_heater" id="rd_heat1" value="Ada" required/>
                                                <label for="rd_heat1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="water_heater" id="rd_heat2" value="Tidak Ada"/>
                                                <label for="rd_heat2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Privat Balkon</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="private_balkon" id="rd_balkon1" value="Ada" required/>
                                                <label for="rd_balkon1">Ada</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="private_balkon" id="rd_balkon2" value="Tidak Ada"/>
                                                <label for="rd_balkon2">Tidak Ada</label>
                                            </div>
                                        </div>
                                        <br>
                                    </div>
                                </div>
                            </fieldset>
                            <div class="modal-footer">
                                <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Tutup</a>
                                <button type="reset" class="btn btn-sm btn-danger" onclick="return confirm('Anda yakin akan reset form?')">Reset</button>
                                <button type="submit" class="btn btn-sm btn-primary m-r-5">Tambah</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>