routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/customer');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('customer', 'CustomersController');
    Route::get('/customer/{id}/delete', 'CustomersController@delete');
    
    Route::resource('payments', 'PaymentsController');
    Route::get('/payments/{id}/delete', 'PaymentsController@delete');
    Route::get('/payments/{id}/receipt', 'PaymentsController@receipt');
    Route::get('/payments/{id}/receipt-dp', 'PaymentsController@receipt_dp');
    Route::get('/payments/{id}/update-dp', 'PaymentsController@update_dp');
    
    Route::resource('occupants', 'OccupantsController');
    Route::get('/occupants/{id}/delete', 'OccupantsController@delete');
    
    Route::resource('room', 'RoomsController');
    Route::get('/room/{id}/delete', 'RoomsController@delete');
    
    Route::resource('room-type', 'RoomTypesController');
    Route::get('/room-type/{id}/delete', 'RoomTypesController@delete');
    
    Route::resource('additional-facilities', 'AdditionalFacilitiesController');
    Route::get('/additional-facilities/{id}/delete', 'AdditionalFacilitiesController@delete');
});

app/Occupants.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Occupants extends Model
{
    protected $fillable = [
        'room_id',
        'customer_id',
        'additional_facilities_id',
        'payment_id',
        'periode',
        'length',
        'due_date',
        'end_date'
    ];

    public function rooms()
    {
        return $this->hasOne('App\Rooms', 'id', 'room_id');
    }

    public function customers()
    {
        return $this->belongsTo('App\Customers', 'customer_id', 'id');
    }

    public function payments()
    {
        return $this->hasOne('App\Payments', 'id', 'payment_id');
    }
}

app/Http/Controllers/OccupantsController.php
<?php

namespace App\Http\Controllers;

use App\Rooms;
use App\Occupants;
use App\Customers;
use App\AdditionalFacilities;
use App\Payments;
use Carbon\Carbon;
use Illuminate\Http\Request;

class OccupantsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['occupants'] = Occupants::all();
        $data['options_room'] = Rooms::select('no_room', 'id')->get();
        $data['options_customer'] = Customers::select('fullname', 'id')->get();
        $data['today'] = Carbon::now()->toDateString();

        return view('occupants.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->periode == 'Harian') {
            $today = Carbon::now()->toDateString();
            $length = Carbon::parse($request->end_date)->diffInDays($today);
            $input_length = "$length Hari";
            $cost = Rooms::where('id', $request->room_id)->first()->value('cost_per_day');
            $price = $length * $cost;
        }
        elseif ($request->periode == 'Bulanan') {
            $today = Carbon::now()->toDateString();
            $length = Carbon::parse($request->end_date)->diffInMonths($today);
            $input_length = "$length Bulan";
            $cost = Rooms::where('id', $request->room_id)->first()->value('cost_per_month');
            $price = $length * $cost;
        }
        elseif ($request->periode == 'Tahunan') {
            $today = Carbon::now()->toDateString();
            $length = Carbon::parse($request->end_date)->diffInYears($today);
            $input_length = "$length Tahun";
            $cost = Rooms::where('id', $request->room_id)->first()->value('cost_per_year');
            $price = $length * $cost;
        }

        $permitted_chars = '123456789ABCDEFGHJKLMNPQRSTUVWXYZ';
        $no_kwitansi = Carbon::now()->format('dmy') . substr(str_shuffle($permitted_chars), 0, 7);
        $no_kwitansi_dp = Carbon::now()->format('dmy') . substr(str_shuffle($permitted_chars), 0, 7);
        
        $req_payments = [
            'no_kwitansi' => $no_kwitansi,
            'no_kwitansi_dp' => $no_kwitansi_dp,
            'dp_booking' => $request->dp_booking,
            'bill' => $price
        ];
        $payment = Payments::create($req_payments);
        $payment_id = $payment->id;

        $req_occupants = [
            'room_id' => $request->room_id,
            'customer_id' => $request->customer_id,
            'additional_facilities_id' => $request->additional_facilities_id,
            'payment_id' => $payment_id,
            'periode' => $request->periode,
            'length' => $input_length,
            'due_date' => $request->due_date,
            'end_date' => $request->end_date
        ];
        $occupant = Occupants::create($req_occupants);
        $occupant_id = $occupant->id;

        Rooms::where('id', $request->room_id)->update(['occupant_id' => $occupant_id]);
        Customers::where('id', $request->customer_id)->update(['occupant_id' => $occupant_id]);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['occupant'] = Occupants::FindOrFail($id);
        return view('occupants.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['occupant'] = Occupants::FindOrFail($id);
        $data['options_room'] = Rooms::select('no_room', 'id')->get();
        $data['options_customer'] = Customers::select('fullname', 'id')->get();

        return view('occupants.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->end_date <= Carbon::now()->toDateString()) {
            Rooms::where('occupant_id', $id)->update(['occupant_id' => null]);
        }
        else {
            Rooms::where('id', $request->room_id)->update(['occupant_id' => $id]);
        }

        if ($request->periode == 'Harian') {
            $today = Carbon::now()->toDateString();
            $length = Carbon::parse($request->end_date)->diffInDays($today);
            $input_length = "$length Hari";
            $cost = Rooms::where('id', $request->room_id)->first()->value('cost_per_day');
            $price = $length * $cost;
        } elseif ($request->periode == 'Bulanan') {
            $today = Carbon::now()->toDateString();
            $length = Carbon::parse($request->end_date)->diffInMonths($today);
            $input_length = "$length Bulan";
            $cost = Rooms::where('id', $request->room_id)->first()->value('cost_per_month');
            $price = $length * $cost;
        } elseif ($request->periode == 'Tahunan') {
            $today = Carbon::now()->toDateString();
            $length = Carbon::parse($request->end_date)->diffInYears($today);
            $input_length = "$length Tahun";
            $cost = Rooms::where('id', $request->room_id)->first()->value('cost_per_year');
            $price = $length * $cost;
        }

        Payments::where('id', $request->payment_id)->update(['bill' => $price]);
        
        $data['all'] = $request->except('_method', '_token');
        $data['length'] = $input_length;
        Occupants::FindOrFail($id)->update($data);
        Customers::where('id', $request->customer_id)->update(['occupant_id' => $id]);

        return redirect('/occupants');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/occupants/add.blade.php
<div class="modal fade" id="modal-add">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Penghuni</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="panel">
                    <div class="panel-body">
                        <form action="{{ route('occupants.store')}}" method="POST" data-parsley-validate="true" enctype="multipart/form-data">
                            @csrf
                            <fieldset>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Kamar</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <select class="form-control selectpicker" name="room_id" data-size="5" data-width="100%" data-live-search="true" data-style="btn-white" required>
                                                    <option value="">- Pilih No Kamar -</option>
                                                    @foreach ($options_room as $room)
                                                    <option value="{{$room->id}}">{{$room->no_room}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Nama Pelanggan</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <select class="form-control selectpicker" name="customer_id" data-size="5" data-width="100%" data-live-search="true" data-style="btn-white" required>
                                                    <option value="">- Pilih Pelanggan -</option>
                                                    @foreach ($options_customer as $customer)
                                                    <option value="{{$customer->id}}">{{$customer->fullname}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Periode Sewa</label>
                                            <span>&nbsp&nbsp&nbsp&nbsp</span>
                                            <div class="checkbox checkbox-css checkbox-inline">
                                                <input type="radio" name="periode" id="rd_periode1" value="Harian" required/>
                                                <label for="rd_periode1">Harian</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="periode" id="rd_periode2" value="Bulanan"/>
                                                <label for="rd_periode2">Bulanan</label>
                                            </div>
                                            <div class="checkbox checkbox-css checkbox-inline"/>
                                                <input type="radio" name="periode" id="rd_periode3" value="Tahunan"/>
                                                <label for="rd_periode3">Tahunan</label>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Tanggal Berakhir</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="end_date" id="datepicker-autoClose1" placeholder="- Pilih Tanggal -" autocomplete="off" required/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">DP Booking</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="dp_booking" placeholder="Contoh: 500000" data-parsley-type="number"/>
                                            </div>
                                        </div>
                                        <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Booking Jatuh Tempo</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <input type="text" class="form-control" name="due_date" id="datepicker-autoClose2" placeholder="- Pilih Tanggal -" autocomplete="off"/>
                                            </div>
                                        </div>
                                        {{-- <div class="form-group row m-b-10">
                                            <label class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-form-label">Fasilitas Tambahan</label>
                                            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                                                <table id="dt_facility" class="table table-bordered table-hover display nowrap">
                                                    <thead>
                                                    </thead>
                                                    <tbody>
                                                        <tr class="table-row" id="">
                                                            <td>
                                                                <select class="form-control selectpicker" data-size="3" data-live-search="true" data-style="btn-white">
                                                                    <option value="">- Pilih Fasilitas -</option>
                                                                    @foreach ($options_facilities as $facilities)
                                                                    <option value="{{$facilities->id}}">{{$facilities->facilities_name}}</option>
                                                                    @endforeach
                                                                </select>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                                <button type="button" onclick="add_facilities()" class="btn btn-sm btn-primary" data-toggle="tooltip"><i class="fa fa-plus-square"></i>&nbsp Tambah Fasilitas Lagi</button>
                                            </div>
                                        </div> --}}
                                        <br>
                                        <div class="note note-warning">
                                            <div class="note-icon"><i class="fa fa-lightbulb"></i></div>
                                            <div class="note-content">
                                                <h4 class="m-t-5 m-b-5 p-b-2">Notes:</h4>
                                                <ul class="m-b-5 p-l-25">
                                                    <li>DP (Down Payment) hanya diperuntukan untuk pelanggan yang hendak booking kamar.</li>
                                                    <li>DP (Down Payment) diisi hanya menggunakan angka tanpa titik.</li>
                                                    <li>Booking jatuh tempo hanya diperuntukan untuk pelanggan yang hendak booking kamar.</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <a href="javascript:;" class="btn btn-white" data-dismiss="modal">Tutup</a>
                                    <button type="reset" class="btn btn-sm btn-danger" onclick="return confirm('Anda yakin akan reset form?')">Reset</button>
                                    <button type="submit" class="btn btn-sm btn-primary m-r-5">Simpan</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/occupants/detail.blade.php
@extends('layouts.app')

@section('sidebar')
@parent
@endsection

@section('content')
<ol class="breadcrumb pull-right">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active">Detail Data Penghuni</li>
</ol>
<h1 class="page-header">Data Penghuni</h1>
<style>
    tfoot input {
    width: 90%;
    padding: 2px;
    box-sizing: border-box;
    }
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-inverse" data-sortable-id="form-stuff-10">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Data Penghuni</h4>
            </div>
            <div class="panel-body">
                <div>
                    <h4><i class="fa fa-id-card fa-fw"></i> Identitas Penghuni</h4>
                </div><br>
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <dl>
                            <dt class="text-inverse">Nama Lengkap</dt>
                            <dd>{{$occupant->customers['fullname']}}</dd>
                            <dt class="text-inverse m-t-10">Nama Panggilan</dt>
                            <dd>{{$occupant->customers['nickname']}}</dd>
                            <dt class="text-inverse m-t-10">No Identitas</dt>
                            <dd>{{$occupant->customers['no_identitas']}}</dd>
                            <dt class="text-inverse m-t-10">Tempat - Tanggal Lahir</dt>
                            <dd>{{$occupant->customers['tempat_lahir']}} - {{$occupant->customers['tanggal_lahir']}}</dd>
                            <dt class="text-inverse m-t-10">No Hp 1 - No Hp 2</dt>
                            <dd>{{$occupant->customers['np_hp1']}} - {{$occupant->customers['np_hp2']}}</dd>
                            <dt class="text-inverse m-t-10">Jenis Kelamin</dt>
                            <dd>{{$occupant->customers['gender']}}</dd>
                            <dt class="text-inverse m-t-10">Foto</dt>
                            <dd><img src="{{ Storage::url('public/profile_photo/'.$occupant->customers['profile_photo']) }}" width="250px" height="250px"/></dd>
                        </dl>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <dl>
                            <dt class="text-inverse m-t-10">Email</dt>
                            <dd>{{$occupant->customers['email']}}</dd>
                            <dt class="text-inverse m-t-10">Pekerjaan</dt>
                            <dd>{{$occupant->customers['job']}}</dd>
                            <dt class="text-inverse m-t-10">Alamat Asal</dt>
                            <dd>{{$occupant->customers['alamat_asal']}}</dd>
                            <dt class="text-inverse m-t-10">Nama Instansi (Sekolah/Kampus/Kantor)</dt>
                            <dd>{{$occupant->customers['nama_instansi']}}</dd>
                            <dt class="text-inverse m-t-10">Alamat Instansi (Sekolah/Kampus/Kantor)</dt>
                            <dd>{{$occupant->customers['alamat_instansi']}}</dd>
                            <dt class="text-inverse m-t-10">No Telp Instansi (Sekolah/Kampus/Kantor)</dt>
                            <dd>{{$occupant->customers['no_telp_instansi']}}</dd>
                        </dl>
                    </div>
                </div><hr />
                <div>
                    <h4><i class="fa fa-bed fa-fw"></i> Detail Kamar</h4>
                </div><br>
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <dl>
                            <dt class="text-inverse">No Kamar</dt>
                            <dd>{{$occupant->rooms['no_room']}}</dd>
                            <dt class="text-inverse">Tipe Kamar</dt>
                            <dd>{{$occupant->rooms->room_types['type_name']}}</dd>
                            <dt class="text-inverse m-t-10">Lokasi Kamar</dt>
                            <dd>{{$occupant->rooms['location']}}</dd>
                        </dl>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <dl>
                            <dt class="text-inverse m-t-10">Ukuran Kamar</dt>
                            <dd>{{$occupant->rooms['size_room']}}</dd>
                            <dt class="text-inverse m-t-10">Keterangan</dt>
                            <dd>{{$occupant->rooms['keterangan']}}</dd>
                        </dl>
                    </div>
                </div><hr />
                <div>
                    <h4><i class="fa fa-wifi fa-fw"></i> Fasilitas Kamar</h4>
                </div><br>
                <div class="row">
                    <div class="col-md-4 col-xs-12">
                        <dl>
                            <dt class="text-inverse">Ukuran Tempat Tidur</dt>
                            <dd>{{$occupant->rooms->room_types['size_bed']}}</dd>
                            <dt class="text-inverse">Meja Belajar</dt>
                            <dd>{{$occupant->rooms->room_types['desk']}}</dd>
                            <dt class="text-inverse m-t-10">Almari</dt>
                            <dd>{{$occupant->rooms->room_types['wardrobe']}}</dd>
                            <dt class="text-inverse m-t-10">AC</dt>
                            <dd>{{$occupant->rooms->room_types['air_conditioner']}}</dd>
                            <dt class="text-inverse m-t-10">Telp Kamar</dt>
                            <dd>{{$occupant->rooms->room_types['line_telp']}}</dd>
                        </dl>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <dl>
                            <dt class="text-inverse m-t-10">Wifi</dt>
                            <dd>{{$occupant->rooms->room_types['wifi']}}</dd>
                            <dt class="text-inverse m-t-10">Kamar Mandi Dalam</dt>
                            <dd>{{$occupant->rooms->room_types['bathroom']}}</dd>
                            <dt class="text-inverse m-t-10">Water Heater</dt>
                            <dd>{{$occupant->rooms->room_types['water_heater']}}</dd>
                            <dt class="text-inverse m-t-10">Privat Balkon</dt>
                            <dd>{{$occupant->rooms->room_types['private_balkon']}}</dd>
                        </dl>
                    </div>
                </div><hr />
                {{-- <div>
                    <h4><i class="fa fa-table fa-fw"></i>List Fasilitas Tambahan</h4>
                </div><br>
                    <table id="table_facility" class="table table-bordered table-hover display nowrap">
                        <thead>
                            <tr>
                                <th style="text-align:center; background:lightgrey;">No</th>
                                <th style="text-align:center; background:lightgrey;">Fasilitas</th>
                                <th style="text-align:center; background:lightgrey;">Keterangan</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="table-row" id="">
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table><hr/>
                </div> --}}
                <div class="btn-group pull-right">
                    <a href="#" class="btn btn-sm btn-info"><i class="fas fa-print"></i> <span>Print</span></a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
@parent
<script>
	$(document).ready(function() {
        $('#table_room').DataTable({
		    'serverside'  : false,
		    'scrollX'     : true,
		    'paging'      : false,
		    'lengthChange': false,
		    'searching'   : false,
		    'ordering'    : true,
		    'info'        : false,
		    'autoWidth'   : false
		});
		$('#table_facility').DataTable({
		    'serverside'  : false,
		    'scrollX'     : true,
		    'paging'      : false,
		    'lengthChange': false,
		    'searching'   : false,
		    'ordering'    : true,
		    'info'        : false,
		    'autoWidth'   : false
		});
	});
</script>
@endsection